name: 'Build & Test'

on: push

jobs:
  unitTest:
    name: "Run Unit Tests"
    runs-on: macos-11
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          flutter pub get


      - name: Run Unit Tests
        run: |
          flutter test