name: 'Build & Test'

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  unitTest:
    name: "Run Unit Tests"
    runs-on: macos-11
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Install Dependencies
        run: |
          flutter pub get

      - name: Run Unit Tests
        run: |
          flutter test